### ISSUE TITLE
Seestadt needs to be split from the Aspern neighborhood

### ISSUE THREAD

**Issue by botic** [apa-newsroom/austrian-neighbourhood-maps#1]
There is no real overlap between the Kleingartensiedlung next to Seestadt in Aspern. You should split them up along the Johann-Kutschera-Gasse, where a green area also will form a boundary in the future.

<img width="813" alt="geojson_io" src="https://user-images.githubusercontent.com/193023/177270313-71a8c8e6-7888-4e11-8614-4148cdabbb63.png">

This line also reflects in local elections: https://medium.com/@botic/die-seestadt-farbentheorie-d2068afbe641

**Comment by mephinet** [comment]
Hi @botic thanks for your valuable input - always great to have local experts looking at our data! We'll add this to our things-to-be-done-before-BP-Wahl todo list...

**Comment by id-has** [comment]
Thanks for the input!
